# Default values for microservice.

replicaCount: 1

image:
  repository: microservice
  pullPolicy: IfNotPresent
  tag: "0.0.1"

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

# ------------ Probes para el microservicio ------------
livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10

# ------------ (Opcional) Volúmenes y mounts si los necesitaras ------------
volumeMounts: {}
volumes: {}
